Please take a look. Thank you.
learn-academy-2021-echo/week-6-assessment-SpiralCode28 pull request #1
Opened 2022-02-07 22:21 UTC by SpiralCode28

I have put examples of some of what we went over during the review... I wanted to get this in by today how it is, per deadline. It is what I had due to the missed time all last week and weekend.

2022-02-07 22:38 UTC, sjproctor requested changes
This looks great so far. Can you take one more pass at any blank problems. I know you're doing a lot of catch up. I think you are very close. I am just seeing the function on #2, adding the expect statements on #3, and the "your answers" on a couple interview questions.

2022-02-07 22:38 UTC, sjproctor commented on code-challenges.test.js
> +});
The test looks great!

2022-02-07 22:38 UTC, sjproctor commented on code-challenges.test.js
> +// }
Nice. These are great process notes.

2022-02-07 22:38 UTC, sjproctor commented on code-challenges.test.js
> +// Expected output: [ 2, 1, -1 ]
Since you have the test variables inside your test you can delete them here.

2022-02-07 22:38 UTC, sjproctor commented on code-challenges.test.js
> +}
Nice!

2022-02-07 22:38 UTC, sjproctor commented on interview-questions.md
> +- The RESTful routes that always need to be passed params are `show`, `update`, `destroy`. The reason is because those methods would need to know what hashes the user wants to execute upon while `ind
Great!

2022-02-07 22:38 UTC, sjproctor commented on interview-questions.md
> +   14. As a user, I can click on the "Create a New List" link and it takes me to a webpage where I see a header with the text, "Create a new Do It list".
Nice work!

2022-02-08 19:13 UTC, SpiralCode28 commented
I will take another pass. Thank you for reviewing.

2022-02-11 21:56 UTC, SpiralCode28 commented
Please review changes. Everything should be completed.

2022-02-11 22:46 UTC, sjproctor approved these changes
Awesome!! Great work, Hannah!

2022-02-11 22:48 UTC, merged